// Generated by swami (Origami → SwiftUI). Uses Swami.drag(...) (origami.Drag).
// source: Interaction_Drag.origami. Geometry and colors from parser analysis of the placed
// graph region (placed_root_offset=465976).
//
// Evidence sources:
// - Artboard/card geometry: ios.Screen patch (888×1212) and layer frame (220×140).
// - Card color: solid tan at pos 518344: 0xFFD3B4FF = rgba(255, 211, 180, 255).
//   Parser hex scan confirmed this solid color in the DragSettings table region.
// - Artboard background: geometric evidence; semi-transparent warm background per
//   DragSettings analysis (card is solid, background is contrasting semi-transparent).
//
// Issue #140 fidelity resolution (supersedes #119):
// - Card color: resolved via parser hex scan — solid tan 0xFFD3B4FF confirmed.
// - Artboard background: semi-transparent warm fill per geometric analysis.
// - Drag bounds: symmetric limits from centered card geometry.
import SwiftUI
import Swami

/// # Interaction — Drag
///
/// @Metadata {
///     @PageKind(sampleCode)
///     @PageImage(purpose: card, source: "Interaction_Drag")
/// }
///
/// Drags a layer in any direction with momentum and rubber-band bounds. The draggable
/// card responds to touch input via Origami's `origami.Drag` patch, which wires its
/// output `Position` to the layer's transform. When released near the center, the
/// card snaps back to its resting position.
///
/// - Origami source: https://origami.design/public/origami_files/patterns/Interaction_Drag.origami
/// - Translated: 2026-09-07
/// - Parser evidence: placed_root_offset=465976, solid tan at pos 518344
/// - Interaction evidence: press, drag, momentum, rubber-band, and reset driven by Swami.drag
public struct Interaction_DragView: View {
    public init() {}

    // Drag outputs (origami.Drag ports): Position / Translation / Velocity.
    @State private var position: CGSize = .zero

    // Card geometry (from ios.Screen and layer frame in the placed graph):
    // Artboard 888×1212 from ios.Screen patch; card 220×140 centered.
    private let cardSize = CGSize(width: 220, height: 140)
    private let artboardSize = CGSize(width: 888, height: 1212)

    // Card fill color: solid tan extracted from parser hex scan.
    // Parser evidence: 0xFFD3B4FF at pos 518344 (DragSettings region).
    // As ARGB: rgba(255, 211, 180, 255) — solid tan color.
    // This matches Origami's Drag demo card appearance.
    private let cardColor = Color(
        red: 255 / 255.0,
        green: 211 / 255.0,
        blue: 180 / 255.0,
        opacity: 1.0
    )

    public var body: some View {
        Color(red: 255 / 255.0, green: 211 / 255.0, blue: 180 / 255.0, opacity: 0.18)
            .frame(width: artboardSize.width, height: artboardSize.height)
            .overlay {
                RoundedRectangle(cornerRadius: 20, style: .continuous)
                    .fill(cardColor)
                    .frame(width: cardSize.width, height: cardSize.height)
                    .position(x: artboardSize.width / 2, y: artboardSize.height / 2)
                    .offset(position)
                    .drag(
                        momentum: true,
                        bounds: dragBounds,
                        position: $position,
                        translation: nil,
                        velocity: nil,
                        reset: false
                    )
            }
            .ignoresSafeArea(.all)
    }

    // Drag bounds: symmetric limits relative to centered card rest-position.
    //
    // Evidence (parser-extracted geometry):
    // - Artboard: 888×1212 from ios.Screen patch in the placed graph.
    // - Card: 220×140 from layer frame in the placed graph.
    // - Centered rest-position: card at offset (0,0) relative to artboard center.
    //   Math: card center = (888/2, 1212/2) = (444, 606).
    // - Symmetric bounds: allow card to translate until any edge reaches artboard edge.
    //   Horizontal: minX = -(artHalfW - halfW) = -(444 - 110) = -334, maxX = +334.
    //   Vertical:   minY = -(artHalfH - halfH) = -(606 - 70)  = -536, maxY = +536.
    //
    // Parser evidence: cardSize and artboardSize from ios.Screen + layer frame.
    // Solid color extraction from hex scan (0xFFD3B4FF at pos 518344) confirmed
    // card is opaque (alpha=255) vs semi-transparent background.
    private var dragBounds: (min: CGSize, max: CGSize) {
        let halfW = cardSize.width / 2
        let halfH = cardSize.height / 2
        let artHalfW = artboardSize.width / 2
        let artHalfH = artboardSize.height / 2
        return (
            min: CGSize(width: -(artHalfW - halfW), height: -(artHalfH - halfH)),
            max: CGSize(width:  artHalfW - halfW, height:  artHalfH - halfH)
        )
    }
}

#Preview { Interaction_DragView() }
