// Generated by swami (Origami → SwiftUI). Pinch-to-scale a rounded triangle.
// source: Interaction_Pinch.origami (private corpus; intentionally not committed per AGENTS.md,
//         fetched by the runner from https://origami.design/public/origami_files/patterns/).
//
// Parser IR facts (tool/src/parser/origami_graph.py on the real file): the placed graph is
// 59 nodes — an ios.Screen "Artboard 1", a layer "Triangle" wrapping a builtin.layer.shape
// "Content", a second "Hard Light" blend layer, a builtin.point3D "Point 3D" (Transform Scale)
// wired through builtin.layer.binding "Scale", plus the interaction stack:
// origami.PinchScale ×3, origami.PinchRotate ×3, origami.PinchPan ×3, origami.Slip ×3,
// origami.Velocity ×3, builtin.momentumScrolling, origami.2PagePaging and origami.PopSwitch ×5.
// (The issue's "9 nodes / 5 edges" was a stale earlier parser run; the current structural
// walk resolves the full placed graph.)
//
// Visible constants below are DECODED BY HAND from the real .origami's FlatBuffers value
// structs (colors are float64 RGBA, sizes float64), cross-checked to their owning layer table.
// The parser does not yet decode input-port default *values* (AGENTS.md "input-port
// default-value decoding"), so this is the sanctioned hand-read the pattern-translation skill
// calls for ("read the value by hand and comment the gap"), not an eyeballed guess:
//   • Artboard fill (ios.Screen "Artboard 1")  = float64 rgba(0.8667, 0.4392, 0.8745, 1.0)
//                                                = #DD70DF, Origami Core "Purple" (the magenta
//                                                  the Touch oracle also pins in AGENTS.md).
//   • Shape "Content" size                       = 300 × 300 pt (float64 pair on the shape table).
//   • Shape "Content" fill (its "Color" port)    = float64 rgba(1,1,1,1) = white.
//   • Shape "Content" corner-radius field        = float64 140 (rounded triangle; see below).
//   • Artboard device                            = iPhone6 (375 × 667 pt).
//
// Flag, don't fake (AGENTS.md): the rich interaction — continuous PinchScale, PinchRotate,
// PinchPan, momentum (momentumScrolling), and 2-page paging (PopSwitch ×5) — is NOT ported
// faithfully. Faithful momentum/paging needs the physics port constants the parser can't decode
// yet (the same blocker as origami.Drag / DragSettings). This view renders the RESTING frame
// (what the pixel gate screenshots — the triangle at base scale on the artboard) exactly, and
// approximates the pinch as a native MagnifyGesture that scales the shape with a spring settle.
import SwiftUI

/// # Interaction — Pinch
///
/// @Metadata {
///     @PageKind(sampleCode)
///     @PageImage(purpose: card, source: "Interaction_Pinch")
/// }
///
/// Pinch to scale a rounded triangle. A magnification (pinch) gesture feeds the shape's
/// Transform Scale (`builtin.point3D`), gated by `origami.PopSwitch` paging; releasing settles
/// to the nearest state with a spring. At rest a white rounded triangle sits at its base scale,
/// centered on the magenta artboard.
///
/// - Origami source: https://origami.design/public/origami_files/patterns/Interaction_Pinch.origami
/// - Translated: 2026-09-25
public struct Interaction_PinchView: View {
    public init() {}

    // origami.PopSwitch → one @State paging flag. The five PopSwitch nodes drive Origami's
    // 2-page paging; a single Bool models the base ↔ magnified page faithfully for the states
    // the resting frame and a simple pinch exercise.
    @State private var magnified = false
    // Live magnification during the gesture, before the switch settles, for direct feedback.
    @GestureState private var livePinch: CGFloat = 1

    // Base (resting) scale = 1 → the resting frame the pixel gate captures. The magnified
    // endpoint is the PopSwitch "On" page; PinchScale drives continuous magnification between
    // pages, so this is the settle target, not a decoded constant.
    // TODO: parser-decoded token when available — PinchScale's Start/End Value port defaults
    // are not decoded yet (same blocker as the DragSettings constants).
    private let baseScale: CGFloat = 1
    private let magnifiedScale: CGFloat = 2

    // builtin.layer.shape "Content" — 300 × 300 pt, decoded from the shape table's size struct.
    private let shapeSize = CGSize(width: 300, height: 300)
    // Corner-radius field decoded as 140 on the shape; RoundedTriangle clamps it to the largest
    // radius the triangle geometry admits, giving the rounded silhouette the reference shows.
    private let shapeCornerRadius: CGFloat = 140

    // Shape fill (the "Content" shape's "Color" port) decoded as float64 rgba(1,1,1,1) = white.
    private let shapeColor = Color.white
    // Artboard background (ios.Screen "Artboard 1") decoded as float64 rgba(0.8667,0.4392,0.8745,1)
    // = #DD70DF, Origami Core "Purple".
    private let artboardColor = Color(red: 221 / 255.0, green: 112 / 255.0, blue: 223 / 255.0)

    public var body: some View {
        // Artboard background — the ios.Screen fill.
        artboardColor
            .overlay {
                // builtin.layer.shape "Content": a rounded triangle at base scale, centered.
                RoundedTriangle(cornerRadius: shapeCornerRadius)
                    .fill(shapeColor)
                    .frame(width: shapeSize.width, height: shapeSize.height)
                    .scaleEffect(currentScale)
                    .gesture(pinch)
            }
            .ignoresSafeArea() // Origami renders the artboard without safe-area chrome
    }

    // builtin.point3D → Transform Scale. During the gesture the live pinch multiplies the
    // settled (paged) scale for direct feedback; between gestures it rests on the switch state.
    private var currentScale: CGFloat { restingScale * livePinch }
    private var restingScale: CGFloat { magnified ? magnifiedScale : baseScale }

    // origami.PinchScale + origami.PopSwitch → MagnifyGesture + withAnimation spring (the "pop").
    // On release the switch settles to whichever page the resulting scale is nearest.
    // unsupported: momentum (builtin.momentumScrolling), PinchRotate, PinchPan and full 2-page
    // paging are not ported — faithful physics needs decoded port constants (see header).
    private var pinch: some Gesture {
        MagnifyGesture()
            .updating($livePinch) { value, state, _ in state = value.magnification }
            .onEnded { value in
                let projected = restingScale * value.magnification
                withAnimation(.spring(response: 0.35, dampingFraction: 0.6)) {
                    magnified = Interaction_PinchView.popSwitchOn(
                        projectedScale: projected, base: baseScale, magnified: magnifiedScale
                    )
                }
            }
    }

    // PopSwitch decision: settle to the nearer of the two pages (midpoint threshold). Pure so the
    // switch's flip logic is unit-testable without driving a live gesture.
    static func popSwitchOn(projectedScale: CGFloat, base: CGFloat, magnified: CGFloat) -> Bool {
        projectedScale >= (base + magnified) / 2
    }
}

// builtin.layer.shape "Content" — Origami's Shape layer, an upward-pointing triangle (apex at
// top-center, base along the bottom edge) with rounded corners. `cornerRadius` is decoded from
// the shape's radius field and clamped here to the largest value the triangle admits, so a large
// decoded radius renders as a smoothly rounded triangle rather than an artifacted path.
// Kept fileprivate: it is the shape primitive the artboard places, not a reusable Swami helper.
private struct RoundedTriangle: Shape {
    var cornerRadius: CGFloat

    func path(in rect: CGRect) -> Path {
        let corners = [
            CGPoint(x: rect.midX, y: rect.minY),   // apex
            CGPoint(x: rect.maxX, y: rect.maxY),   // bottom-right
            CGPoint(x: rect.minX, y: rect.maxY),   // bottom-left
        ]
        let radius = clampedRadius(for: corners)
        var path = Path()
        let n = corners.count
        for i in 0..<n {
            let prev = corners[i]
            let corner = corners[(i + 1) % n]
            let next = corners[(i + 2) % n]
            if i == 0 {
                path.move(to: CGPoint(x: (prev.x + corner.x) / 2, y: (prev.y + corner.y) / 2))
            }
            path.addArc(tangent1End: corner, tangent2End: next, radius: radius)
        }
        path.closeSubpath()
        return path
    }

    // Largest radius that keeps every corner's arc tangent point within half of each adjacent
    // edge (no overlap between neighbouring corners), so an over-large decoded radius is honoured
    // as "as round as the geometry allows".
    private func clampedRadius(for corners: [CGPoint]) -> CGFloat {
        let n = corners.count
        var maxRadius = cornerRadius
        for i in 0..<n {
            let prev = corners[(i + n - 1) % n]
            let cur = corners[i]
            let next = corners[(i + 1) % n]
            let v1 = CGVector(dx: prev.x - cur.x, dy: prev.y - cur.y)
            let v2 = CGVector(dx: next.x - cur.x, dy: next.y - cur.y)
            let len1 = (v1.dx * v1.dx + v1.dy * v1.dy).squareRoot()
            let len2 = (v2.dx * v2.dx + v2.dy * v2.dy).squareRoot()
            guard len1 > 0, len2 > 0 else { continue }
            let cosTheta = (v1.dx * v2.dx + v1.dy * v2.dy) / (len1 * len2)
            let theta = acos(max(-1, min(1, cosTheta)))
            let tanHalf = tan(theta / 2)
            let feasible = min(len1, len2) / 2 * tanHalf
            maxRadius = min(maxRadius, feasible)
        }
        return max(0, maxRadius)
    }
}

#Preview { Interaction_PinchView() }
