// Generated by swami (Origami → SwiftUI). Uses Swami.drag(...) (origami.Drag).
// source: Interaction_Drag.origami. Geometry from artboard (888×1212); card color
// extracted from graph (tan #B0E0B27B → rgb 224,178,123). Bounds derived from
// card size relative to artboard (centered draggable card with rubber-band edges).
import SwiftUI
import Swami

/// # Interaction — Drag
///
/// @Metadata {
///     @PageKind(sampleCode)
///     @PageImage(purpose: card, source: "Interaction_Drag")
/// }
///
/// Drags a layer in any direction with momentum and rubber-band bounds. The draggable
/// card responds to touch input via Origami's `origami.Drag` patch, which wires its
/// output `Position` to the layer's transform. When released near the center, the
/// card snaps back to its resting position.
///
/// - Origami source: https://origami.design/public/origami_files/patterns/Interaction_Drag.origami
/// - Translated: 2026-09-07
public struct Interaction_DragView: View {
    public init() {}

    // Drag outputs (origami.Drag ports): Position / Translation / Velocity.
    @State private var position: CGSize = .zero

    // Card geometry (derived from artboard centering): 220×140 centered on 888×1212 artboard.
    private let cardSize = CGSize(width: 220, height: 140)
    // Artboard matches Origami's canvas (888×1212 from ios.Screen).
    private let artboardSize = CGSize(width: 888, height: 1212)
    // Card fill color extracted from graph: #B0E0B27B (tan/sand).
    private let cardColor = Color(
        red: 224 / 255.0,
        green: 178 / 255.0,
        blue: 123 / 255.0,
        opacity: 176 / 255.0
    )

    public var body: some View {
        // Artboard background — matches Origami's canvas color.
        // TODO: parser-decoded token — the artboard fill color was not yet readable from
        // the parser's placed-graph walk; the literal rgb(235,57,30)/42α is a placeholder
        // awaiting token (ColorKit) name or hex extraction from the .origami graph.
        Color(red: 235 / 255.0, green: 57 / 255.0, blue: 30 / 255.0, opacity: 42 / 255.0)
            .overlay {
                // Draggable card centered on artboard.
                RoundedRectangle(cornerRadius: 20, style: .continuous)
                    .fill(cardColor)
                    .frame(width: cardSize.width, height: cardSize.height)
                    // origami.Drag patch: momentum enabled, rubber-band bounds,
                    // Position output feeds the card's offset.
                    .drag(
                        momentum: true,
                        bounds: dragBounds,
                        position: $position
                    )
            }
            .frame(width: artboardSize.width, height: artboardSize.height)
            .ignoresSafeArea() // Origami renders without safe-area chrome
    }

    // Drag bounds: keep the card fully on-screen relative to its resting center.
    private var dragBounds: (min: CGSize, max: CGSize) {
        let halfW = cardSize.width / 2
        let halfH = cardSize.height / 2
        let artHalfW = artboardSize.width / 2
        let artHalfH = artboardSize.height / 2
        return (
            min: CGSize(width: -(artHalfW - halfW), height: -(artHalfH - halfH)),
            max: CGSize(width:  artHalfW - halfW, height:  artHalfH - halfH)
        )
    }
}

#Preview { Interaction_DragView() }
