// Generated by swami (Origami → SwiftUI). origami.PopSwitch → @State toggled by a pinch
// (MagnifyGesture, SwiftUI's current name for the pinch gesture Origami exposes as
// Magnification; the older MagnificationGesture is deprecated on this deployment target).
// source: Interaction_Pinch.origami (private corpus; intentionally not committed per AGENTS.md).
//
// Parser IR facts (tool/src/parser/origami_graph.py): 9 placed nodes / 5 edges —
// ios.Screen ×1, builtin.layer.layer ×2, builtin.layer.shape ×1, builtin.layer.binding ×2,
// origami.PopSwitch ×2, builtin.point3D ×1. Mechanism: a magnification (pinch) gesture flips
// the PopSwitch state, which drives the shape's Transform Scale — a builtin.point3D whose X/Y
// components are the two PopSwitch outputs. The two builtin.layer.binding nodes wire that scale
// onto the shape layer. The RESTING frame (what the pixel gate screenshots) is the shape at its
// base scale on the artboard background.
//
// Flag, don't fake (AGENTS.md): the parser emits node types/names only — it does not yet decode
// color tokens, layer frames, or input-port default *values* (the same blocker as
// Interaction_Drag and the DragSettings TODO in AGENTS.md). So the artboard color, shape fill,
// shape size, and the magnified-scale endpoint below are documented placeholders marked
// `TODO: parser-decoded token when available`, not values read from the graph.
import SwiftUI

/// # Interaction — Pinch
///
/// @Metadata {
///     @PageKind(sampleCode)
///     @PageImage(purpose: card, source: "Interaction_Pinch")
/// }
///
/// Pinch to scale a shape. A magnification (pinch) gesture drives an `origami.PopSwitch` whose
/// state feeds the shape's Transform Scale (`builtin.point3D`); releasing the pinch "pops" the
/// switch to its nearest state with a spring. At rest the shape sits at its base scale on the
/// artboard background.
///
/// - Origami source: https://origami.design/public/origami_files/patterns/Interaction_Pinch.origami
/// - Translated: 2026-09-25
public struct Interaction_PinchView: View {
    public init() {}

    // origami.PopSwitch ×2 → one @State. The two switches carry the X and Y components of the
    // scale point3D; a uniform pinch flips them together, so a single Bool models both faithfully.
    @State private var magnified = false
    // Live magnification during the gesture, before the switch pops, for direct visual feedback.
    @GestureState private var livePinch: CGFloat = 1

    // Base (resting) scale and the PopSwitch "On" scale.
    // TODO: parser-decoded token when available — the magnified endpoint is an input-port default
    // *value* on the PopSwitch/point3D that the parser does not decode yet (see AGENTS.md
    // "input-port default-value decoding"). 2× is a documented placeholder, not a read fact.
    private let baseScale: CGFloat = 1
    private let magnifiedScale: CGFloat = 2

    // builtin.layer.shape — the scaled shape. Size is a placeholder pending parser frame decode.
    // TODO: parser-decoded token when available — layer frame not decoded from the placed graph.
    private let shapeSize = CGSize(width: 200, height: 200)

    // Shape fill (builtin.layer.shape) and artboard background (ios.Screen / builtin.layer.layer).
    // TODO: parser-decoded token when available — the parser does not yet emit color value objects
    // with a known channel order (same gap recorded for Interaction_Drag). Placeholders below.
    private let shapeColor = Color(red: 76 / 255.0, green: 141 / 255.0, blue: 255 / 255.0)
    private let artboardColor = Color(red: 239 / 255.0, green: 239 / 255.0, blue: 244 / 255.0)

    public var body: some View {
        // Artboard background — the ios.Screen / backing layer fill.
        artboardColor
            .overlay {
                // builtin.layer.shape at its base scale, centered on the artboard.
                RoundedRectangle(cornerRadius: 20, style: .continuous)
                    .fill(shapeColor)
                    .frame(width: shapeSize.width, height: shapeSize.height)
                    .scaleEffect(currentScale)
                    .gesture(pinch)
            }
            .ignoresSafeArea() // Origami renders the artboard without safe-area chrome
    }

    // builtin.point3D → Transform Scale. During the gesture the live pinch multiplies the
    // committed (popped) scale for direct feedback; between gestures it rests on the switch state.
    private var currentScale: CGFloat { restingScale * livePinch }
    private var restingScale: CGFloat { magnified ? magnifiedScale : baseScale }

    // origami.PopSwitch → MagnifyGesture + withAnimation spring (the "pop"). On release the switch
    // flips to whichever state the resulting scale is nearest, then springs into place.
    private var pinch: some Gesture {
        MagnifyGesture()
            .updating($livePinch) { value, state, _ in state = value.magnification }
            .onEnded { value in
                let projected = restingScale * value.magnification
                withAnimation(.spring(response: 0.35, dampingFraction: 0.6)) {
                    magnified = Interaction_PinchView.popSwitchOn(
                        projectedScale: projected, base: baseScale, magnified: magnifiedScale
                    )
                }
            }
    }

    // PopSwitch decision: snap to the nearer of the two states (midpoint threshold). Pure so the
    // switch's flip logic is unit-testable without driving a live gesture.
    static func popSwitchOn(projectedScale: CGFloat, base: CGFloat, magnified: CGFloat) -> Bool {
        projectedScale >= (base + magnified) / 2
    }
}

#Preview { Interaction_PinchView() }
