// Generated by swami (Origami → SwiftUI). Uses Swami.drag(...) (origami.Drag).
// source: Interaction_Swipe.origami.
// Placed graph (deterministic parser): 65 nodes / single ios.Screen —
//   builtin.layer.layer ×2, builtin.layer.image ×2, builtin.layer.ellipse ×1,
//   builtin.layer.fill ×1, builtin.layer.interaction ×2, builtin.point3D ×2,
//   origami.PopSwitch ×5, origami.PinchScale/PinchRotate/PinchPan ×3 each,
//   origami.Slip ×3, origami.Velocity ×3, builtin.momentumScrolling ×1,
//   builtin.transition ×1.
// Mechanism: a horizontal swipe (drag with velocity + momentum + slip) drives the
// photo layers' position between resting pages. The resting frame — what the pixel
// gate screenshots — is the content at rest on the artboard: the current photo
// centered on the background fill, the adjacent photo off-screen.
//
// PRIMARY GESTURE (translated): the swipe. builtin.momentumScrolling + origami.Velocity
// + origami.Slip is exactly Origami's Drag momentum stack, which the Swami `.drag(…)`
// helper already ports from origami.Drag's own graph — so the swipe maps to `.drag`
// with momentum on, bounds constrained to the horizontal axis (a swipe pages sideways,
// not vertically).
//
// SECONDARY GESTURE MACHINERY (flagged, not faked — AGENTS.md "flag, don't fake"):
// - origami.PinchScale / PinchRotate / PinchPan (×3 each): a photo-zoom/rotate/pan
//   gesture layered on top of the swipe. No faithful native mapping and no shipped
//   Swami helper composes all three with the swipe's arbitration; flagged inline
//   below rather than approximated.
// - origami.PopSwitch ×5: the per-page snap/latched state the swipe lands on. Only the
//   primary rest page is reproduced; the full snap-state machine is a port-default the
//   parser can't read yet.
// - builtin.transition ×1: an interpolation on a driven value; not reproduced pending
//   the driving edge being decoded.
//
// Fidelity debts (flag, don't fake — AGENTS.md):
// - Two builtin.layer.image layers are proprietary photo assets that cannot be
//   reproduced from the placed-graph walk. Rendered as flagged placeholders (a neutral
//   fill marked with a photo glyph), NOT faked with a stand-in image. The resting
//   layout (current photo centered, next photo off-screen right) is structural.
// - builtin.layer.fill background color, builtin.layer.ellipse geometry, and the exact
//   artboard/photo sizes live as port defaults the parser can't decode yet → TODO
//   markers inline, placeholder values chosen structurally.
import SwiftUI
import Swami

/// # Interaction — Swipe
///
/// @Metadata {
///     @PageKind(sampleCode)
///     @PageImage(purpose: card, source: "Interaction_Swipe")
/// }
///
/// Swipe horizontally to page between photos. The swipe is Origami's momentum-scrolling
/// Drag stack (`builtin.momentumScrolling` + `origami.Velocity` + `origami.Slip`), which
/// maps onto the Swami `.drag(…)` helper with momentum on and bounds locked to the
/// horizontal axis. At rest the current photo sits centered on the background fill.
///
/// - Origami source: https://origami.design/public/origami_files/patterns/Interaction_Swipe.origami
/// - Translated: 2026-09-28
///
/// This view is a worked example of the swipe → `origami.Drag` mapping, not shipped API.
/// It stays `public` only so the verification host can instantiate it, and is hidden from
/// the generated docs (`@_documentation`) — the reader-facing page is the standalone
/// `Swami.docc/Patterns/Interaction_Swipe.md`, which centers the patch, not this struct.
@_documentation(visibility: internal)
public struct Interaction_SwipeView: View {
    public init() {}

    // origami.Drag output (Position). The horizontal swipe drives it; momentum + slip
    // carry the throw after release, then it settles on the nearest page.
    @State private var position: CGSize = .zero

    // Artboard matches Origami's canvas. Exact size is a port default the parser can't
    // read yet; a page spans the full artboard width.
    // TODO: parser-decoded token when available — artboard size not decoded.
    private let artboardSize = CGSize(width: 393, height: 852)

    // builtin.layer.image ×2 → two paged photos.
    private let pageCount = 2

    public var body: some View {
        // builtin.layer.fill — full-bleed background.
        // TODO: parser-decoded token when available — the fill's color is a port default
        // the parser can't read yet; black is a structural placeholder for a photo viewer.
        Color.black
            .overlay {
                // builtin.layer.layer ×2 → container groups (the paged photo row + overlay).
                ZStack {
                    // builtin.layer.image ×2, positioned side by side and paged by the swipe.
                    // builtin.point3D ×2 → each photo's Transform Position; the swipe offsets
                    // the whole row so page N rests centered.
                    HStack(spacing: 0) {
                        ForEach(0..<pageCount, id: \.self) { _ in
                            photoPlaceholder
                                .frame(width: artboardSize.width, height: artboardSize.height)
                        }
                    }
                    .frame(width: artboardSize.width, alignment: .leading)
                    // origami.Drag (swipe): momentum on, bounds locked to the horizontal
                    // axis so the row pages sideways only. Velocity + Slip + momentumScrolling
                    // are the helper's momentum stack.
                    .drag(momentum: true, bounds: swipeBounds, position: $position)

                    // builtin.layer.ellipse — a single ellipse on the artboard.
                    // TODO: parser-decoded token when available — the ellipse's size, fill,
                    // and position are port defaults the parser can't read yet; rendered as a
                    // small centered indicator dot as a structural placeholder.
                    Ellipse()
                        .fill(.white.opacity(0.9))
                        .frame(width: 8, height: 8)
                        .offset(y: artboardSize.height / 2 - 40)

                    // unsupported: origami.PinchScale / PinchRotate / PinchPan (×3 each) —
                    // secondary photo zoom/rotate/pan gesture. No faithful native mapping and
                    // no shipped Swami helper composes all three with the swipe's arbitration.
                    // unsupported: origami.PopSwitch ×5 — per-page latched snap state; only the
                    // primary rest page is reproduced (port defaults undecoded).
                    // unsupported: builtin.transition ×1 — interpolation on a driven value;
                    // the driving edge is not decoded yet.
                }
                .clipped()
            }
            .frame(width: artboardSize.width, height: artboardSize.height)
            .ignoresSafeArea() // Origami renders the artboard without safe-area chrome
            .statusBarHidden(true) // Origami's artboard render has no iOS status bar
    }

    // builtin.layer.image → a proprietary photo asset that can't be reproduced from the
    // placed-graph walk. Flagged placeholder (neutral fill + photo glyph), not a faked
    // stand-in image (AGENTS.md "flag, don't fake").
    private var photoPlaceholder: some View {
        Rectangle()
            .fill(Color(white: 0.15))
            .overlay(
                Image(systemName: "photo")
                    .font(.system(size: 44, weight: .regular))
                    .foregroundStyle(.white.opacity(0.35))
            )
    }

    // origami.Drag bounds for the swipe: horizontal only. The photo row is `pageCount`
    // pages wide; page 0 rests at offset 0 and each further page shifts the row left by
    // one artboard width. Vertical extent is pinned to 0 so a swipe never drifts up/down.
    private var swipeBounds: (min: CGSize, max: CGSize) {
        Self.horizontalSwipeBounds(pageWidth: artboardSize.width, pageCount: pageCount)
    }

    // Factored out so the horizontal-only paging math is testable without the view.
    static func horizontalSwipeBounds(pageWidth: CGFloat, pageCount: Int) -> (min: CGSize, max: CGSize) {
        let travel = pageWidth * CGFloat(max(pageCount - 1, 0))
        return (
            min: CGSize(width: -travel, height: 0),
            max: CGSize(width: 0, height: 0)
        )
    }
}

#Preview { Interaction_SwipeView() }
