// Generated by swami (Origami → SwiftUI).
// source: Interaction_Drag.origami
import SwiftUI
import Swami

/// # Interaction — Drag
///
/// @Metadata {
///     @PageKind(sampleCode)
///     @PageImage(purpose: card, source: "Interaction_Drag")
/// }
///
/// Reproduces the runner reference's fixed layer hierarchy and framing: a full-screen
/// magenta canvas and a centered white card. The card maps `origami.Drag` Position to
/// its offset. Release projects momentum, applies the Drag patch's logical bounds, and
/// pulses Reset when both position axes are within the placed graph's 100-point center
/// tolerance.
public struct Interaction_DragView: View {
    public init() {}

    /// Revision-specific contract checked by SwamiHost before CI can capture this view.
    /// Changing Interaction Drag's committed composition requires changing this value
    /// and the host assertion together, preventing a stale linked framework from passing.
    public static let renderSignature = "interaction-drag-r140-canvas-card-v4"

    @State private var position: CGSize = .zero
    @State private var translation: CGSize = .zero
    @State private var velocity: CGSize = .zero
    @State private var resetCount: UInt = 0

    static let referenceSize = CGSize(width: 375, height: 667)
    static let canvasColor = Color(
        .sRGB,
        red: 221.0 / 255.0,
        green: 112.0 / 255.0,
        blue: 223.0 / 255.0,
        opacity: 1
    )
    static let cardSize: CGFloat = 120
    static let cardCornerRadius: CGFloat = 15
    static let resetTolerance: CGFloat = 100
    // Origami's Drag patch documentation specifies 0.15. Requiring this at the
    // helper call site prevents an unproven, implicit iOS-style fallback.
    static let rubberBandFriction: CGFloat = 0.15

    /// Non-visual geometry recovered from the placed graph. The logical region
    /// constrains Drag state only; it is deliberately absent from `body`.
    enum DragGeometry {
        static let logicalRegion = CGSize(width: 315, height: 607)
        static let bounds = (
            min: CGSize(
                width: -(logicalRegion.width - Interaction_DragView.cardSize) / 2,
                height: -(logicalRegion.height - Interaction_DragView.cardSize) / 2
            ),
            max: CGSize(
                width: (logicalRegion.width - Interaction_DragView.cardSize) / 2,
                height: (logicalRegion.height - Interaction_DragView.cardSize) / 2
            )
        )
    }

    public var body: some View {
        ZStack {
            Self.canvasColor

            RoundedRectangle(cornerRadius: Self.cardCornerRadius)
                .fill(.white)
                .frame(width: Self.cardSize, height: Self.cardSize)
                .contentShape(Rectangle())
                .accessibilityIdentifier("interaction-drag-card")
                .drag(
                    momentum: true,
                    bounds: Self.DragGeometry.bounds,
                    rubberBandFriction: Self.rubberBandFriction,
                    position: $position,
                    translation: $translation,
                    velocity: $velocity,
                    resetCount: resetCount,
                    onRelease: pulsePlacedGraphReset
                )
        }
        .frame(width: Self.referenceSize.width, height: Self.referenceSize.height)
        .ignoresSafeArea(.all)
        .statusBarHidden(true)
        .accessibilityValue(Self.renderSignature)
    }

    static func shouldReset(_ position: CGSize) -> Bool {
        abs(position.width) <= resetTolerance && abs(position.height) <= resetTolerance
    }

    private func pulsePlacedGraphReset(at releasedPosition: CGSize) {
        guard Self.shouldReset(releasedPosition) else { return }
        resetCount &+= 1
    }
}

#Preview { Interaction_DragView() }
