// Generated by swami (Origami → SwiftUI).
// source: Touch Origami Example. Geometry is graph-derived; color hexes marked
// (approx) in the IR still need exact extraction from the graph.
import SwiftUI

enum OrigamiInteraction { case tap, press, doubleTap, longPress }

/// One Origami Frame (card) with a 100×100 Oval whose Transform Scale is
/// driven 0…endScale by an interaction patch (Classic Animation, quadratic).
struct InteractionCard: View {
    let title: String
    let cardColor: Color
    let ovalColor: Color
    let interaction: OrigamiInteraction
    let momentary: Bool
    let endScale: CGFloat      // Transition End = 5
    let animation = Animation.easeInOut(duration: 0.5)

    // Transform Scale output. Origami rest value = 0 (Oval invisible until touched).
    @State private var ovalScale: CGFloat = 0

    var body: some View {
        RoundedRectangle(cornerRadius: 20, style: .continuous)
            .fill(cardColor)
            .frame(maxWidth: .infinity)
            .frame(height: 168)                       // Frame: Grow (approx height in layout)
            .overlay {
                Circle()                              // Oval layer, 100×100
                    .fill(ovalColor)
                    .frame(width: 100, height: 100)
                    .scaleEffect(ovalScale)           // Transform Scale patch (0…endScale)
            }
            .overlay { Text(title).font(.headline).foregroundStyle(labelColor) }
            .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
            .contentShape(Rectangle())
            .modifier(InteractionGesture(interaction: interaction, momentary: momentary,
                                         endScale: endScale, animation: animation,
                                         scale: $ovalScale))
    }

    private var labelColor: Color {
        cardColor.isApproximatelyWhite ? Color(red: 0.85, green: 0.20, blue: 0.70) : .white.opacity(0.95)
    }
}

/// Interaction patch → SwiftUI gesture. Drives the Oval scale between 0 and endScale.
private struct InteractionGesture: ViewModifier {
    let interaction: OrigamiInteraction
    let momentary: Bool
    let endScale: CGFloat
    let animation: Animation
    @Binding var scale: CGFloat

    @ViewBuilder func body(content: Content) -> some View {
        switch interaction {
        case .tap:       content.onTapGesture { pulse() }
        case .doubleTap: content.onTapGesture(count: 2) { pulse() }
        case .press:
            content.gesture(DragGesture(minimumDistance: 0)
                .onChanged { _ in set(endScale) }.onEnded { _ in set(0) })
        case .longPress:
            content.gesture(LongPressGesture(minimumDuration: 0.3)
                .onChanged { _ in set(endScale) }.onEnded { _ in set(0) }
                .simultaneously(with: DragGesture(minimumDistance: 0).onEnded { _ in set(0) }))
        }
    }
    private func set(_ v: CGFloat) { withAnimation(animation) { scale = v } }
    private func pulse() {
        withAnimation(animation) { scale = endScale }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.20) { withAnimation(animation) { scale = 0 } }
    }
}

/// Artboard 1 → Group (vertical stack of cards).
struct TouchOrigamiExampleView: View {
    var body: some View {
        VStack(spacing: 30) {
            InteractionCard(title: "Tap",
                            cardColor: Color(hex: "#FFFFFF"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .tap, momentary: true,
                            endScale: 5)
            InteractionCard(title: "Down",
                            cardColor: Color(hex: "#F5D9F0"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .press, momentary: false,
                            endScale: 5)
            InteractionCard(title: "Double Tap",
                            cardColor: Color(hex: "#EEC6E8"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .doubleTap, momentary: true,
                            endScale: 5)
            InteractionCard(title: "Long Press",
                            cardColor: Color(hex: "#E7B6DE"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .longPress, momentary: false,
                            endScale: 5)
        }
        .padding(.horizontal, 16)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color(hex: "#DD70DF"))    // Artboard background (hex approx — parser target)
    }
}

extension Color {
    init(hex: String) {
        let h = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let v = UInt64(h, radix: 16) ?? 0xFFFFFF
        self.init(.sRGB, red: Double((v>>16)&0xFF)/255, green: Double((v>>8)&0xFF)/255,
                  blue: Double(v&0xFF)/255, opacity: 1)
    }
    var isApproximatelyWhite: Bool {
        #if canImport(UIKit)
        var r: CGFloat=0,g: CGFloat=0,b: CGFloat=0,a: CGFloat=0
        UIColor(self).getRed(&r,green:&g,blue:&b,alpha:&a); return r>0.9&&g>0.9&&b>0.9
        #else
        return false
        #endif
    }
}

#Preview { TouchOrigamiExampleView() }
