// Generated by swami (Origami → SwiftUI). Uses OrigamiPatterns.Interaction (.interaction()).
// source: Touch Origami Example. Geometry graph-derived; colors exact.
import SwiftUI

enum OrigamiInteraction { case tap, press, doubleTap, longPress }

/// Origami Frame (card) with a 100×100 Oval whose Transform Scale is driven 0…endScale
/// by the Interaction patch, positioned at the touch point (Sample and Hold → Position).
struct InteractionCard: View {
    let title: String
    let cardColor: Color
    let ovalColor: Color
    let interaction: OrigamiInteraction
    let endScale: CGFloat        // Transition End = 5
    let animation = Animation.easeInOut(duration: 0.5)

    @State private var ovalScale: CGFloat = 0     // Transform Scale, rest = 0
    @State private var ovalCenter: CGPoint? = nil // Sample and Hold → Oval Position
    @State private var isDown = false             // Interaction 'Down' output

    var body: some View {
        ZStack {
            RoundedRectangle(cornerRadius: 20, style: .continuous)
                .fill(cardColor)
            GeometryReader { geo in
                Circle()
                    .fill(ovalColor)
                    .frame(width: 100, height: 100)
                    .scaleEffect(ovalScale)
                    .position(ovalCenter ?? CGPoint(x: geo.size.width / 2,
                                                     y: geo.size.height / 2))
            }
            Text(title).font(.headline).foregroundStyle(labelColor)
        }
        .frame(maxWidth: .infinity).frame(height: 116)
        .clipShape(RoundedRectangle(cornerRadius: 20, style: .continuous))
        // Interaction patch → gesture outputs (only the requested one is attached).
        .interaction(
            down:        interaction == .press      ? $isDown : nil,
            position:    $ovalCenter,
            onTap:       interaction == .tap        ? { pulse() } : nil,
            onDoubleTap: interaction == .doubleTap  ? { pulse() } : nil,
            onLongPress: interaction == .longPress  ? { pulse() } : nil
        )
        // 'Down' held → grow while pressed (Classic Animation), settle on release.
        .onChange(of: isDown) { _, d in
            withAnimation(animation) { ovalScale = d ? endScale : 0 }
        }
    }

    private var labelColor: Color {
        cardColor.isApproximatelyWhite ? Color(red: 0.85, green: 0.20, blue: 0.70) : .white.opacity(0.95)
    }
    // Momentary pulse (Tap / Double Tap / Long Press): grow, then settle back.
    private func pulse() {
        withAnimation(animation) { ovalScale = endScale }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) { withAnimation(animation) { ovalScale = 0 } }
    }
}

/// Artboard 1 → Group (vertical stack of cards).
struct TouchOrigamiExampleView: View {
    var body: some View {
        VStack(spacing: 30) {
            InteractionCard(title: "Tap",
                            cardColor: Color(hex: "#FFFFFF"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .tap, endScale: 5)
            InteractionCard(title: "Down",
                            cardColor: Color(hex: "#F5D9F0"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .press, endScale: 5)
            InteractionCard(title: "Double Tap",
                            cardColor: Color(hex: "#EEC6E8"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .doubleTap, endScale: 5)
            InteractionCard(title: "Long Press",
                            cardColor: Color(hex: "#E7B6DE"),
                            ovalColor: Color(hex: "#DD70DF"),
                            interaction: .longPress, endScale: 5)
        }
        .padding(.horizontal, 16)
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color(hex: "#DD70DF"))
    }
}

extension Color {
    init(hex: String) {
        let h = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let v = UInt64(h, radix: 16) ?? 0xFFFFFF
        self.init(.sRGB, red: Double((v>>16)&0xFF)/255, green: Double((v>>8)&0xFF)/255,
                  blue: Double(v&0xFF)/255, opacity: 1)
    }
    var isApproximatelyWhite: Bool {
        #if canImport(UIKit)
        var r: CGFloat=0,g: CGFloat=0,b: CGFloat=0,a: CGFloat=0
        UIColor(self).getRed(&r,green:&g,blue:&b,alpha:&a); return r>0.9&&g>0.9&&b>0.9
        #else
        return false
        #endif
    }
}

#Preview { TouchOrigamiExampleView() }
