#!/usr/bin/env python3
"""
swiftgen — Origami IR -> SwiftUI codegen.

Graph-faithful model (values read from the document). Uses the Swami helpers
(named after Origami patches, bare, ADR-0010) — here, the `.interaction()` modifier — so the
generated code reads like the patch graph and the helper encapsulates the gesture wiring.
"""
import json, sys, pathlib

CURVE = {"quadratic": "easeInOut", "linear": "linear"}

def load(p): return json.loads(pathlib.Path(p).read_text())

def gen(ir):
    G = ir["group"]; F = ir["frame_defaults"]; O = ir["oval_defaults"]; AN = ir["animation"]
    A = ir["artboard"]; rows = ir["rows"]
    anim = f'Animation.{CURVE.get(AN["curve"],"easeInOut")}(duration: {AN["duration"]})'
    r = F["cornerRadius"]
    L=[]; add=L.append

    add("// Generated by swami (Origami → SwiftUI). Uses Swami.Interaction (.interaction()).")
    add(f"// source: {ir['document']['name']}. Geometry graph-derived; colors exact.")
    add("import SwiftUI")
    add("")
    add("enum OrigamiInteraction { case tap, press, doubleTap, longPress }")
    add("")
    add("/// Origami Frame (card) with a 100×100 Oval whose Transform Scale is driven 0…endScale")
    add("/// by the Interaction patch, positioned at the touch point (Sample and Hold → Position).")
    add("struct InteractionCard: View {")
    add("    let title: String")
    add("    let cardColor: Color")
    add("    let ovalColor: Color")
    add("    let interaction: OrigamiInteraction")
    add(f"    let endScale: CGFloat        // Transition End = {AN['endScale']}")
    add(f"    let animation = {anim}")
    add("")
    add("    @State private var ovalScale: CGFloat = 0     // Transform Scale, rest = 0")
    add("    @State private var ovalCenter: CGPoint? = nil // Sample and Hold → Oval Position")
    add("    @State private var isDown = false             // Interaction 'Down' output")
    add("")
    add("    var body: some View {")
    add("        ZStack {")
    add(f"            RoundedRectangle(cornerRadius: {r}, style: .continuous)")
    add("                .fill(cardColor)")
    add("            GeometryReader { geo in")
    add("                Circle()")
    add("                    .fill(ovalColor)")
    add(f"                    .frame(width: {O['width']}, height: {O['height']})")
    add("                    .scaleEffect(ovalScale)")
    add("                    .position(ovalCenter ?? CGPoint(x: geo.size.width / 2,")
    add("                                                     y: geo.size.height / 2))")
    add("            }")
    add("            Text(title).font(.headline).foregroundStyle(labelColor)")
    add("        }")
    add("        .frame(maxWidth: .infinity).frame(height: 116)")
    add(f"        .clipShape(RoundedRectangle(cornerRadius: {r}, style: .continuous))")
    add("        // Interaction patch → gesture outputs (only the requested one is attached).")
    add("        .interaction(")
    add("            down:        interaction == .press      ? $isDown : nil,")
    add("            position:    $ovalCenter,")
    add("            onTap:       interaction == .tap        ? { pulse() } : nil,")
    add("            onDoubleTap: interaction == .doubleTap  ? { pulse() } : nil,")
    add("            onLongPress: interaction == .longPress  ? { pulse() } : nil")
    add("        )")
    add("        // 'Down' held → grow while pressed (Classic Animation), settle on release.")
    add("        .onChange(of: isDown) { _, d in")
    add("            withAnimation(animation) { ovalScale = d ? endScale : 0 }")
    add("        }")
    add("    }")
    add("")
    add("    private var labelColor: Color {")
    add("        cardColor.isApproximatelyWhite ? Color(red: 0.85, green: 0.20, blue: 0.70) : .white.opacity(0.95)")
    add("    }")
    add("    // Momentary pulse (Tap / Double Tap / Long Press): grow, then settle back.")
    add("    private func pulse() {")
    add("        withAnimation(animation) { ovalScale = endScale }")
    add("        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) { withAnimation(animation) { ovalScale = 0 } }")
    add("    }")
    add("}")
    add("")
    add("/// Artboard 1 → Group (vertical stack of cards).")
    add("public struct TouchOrigamiExampleView: View {")
    add("    public init() {}")
    add("    public var body: some View {")
    add(f"        VStack(spacing: {G['spacing']}) {{")
    for row in rows:
        gc = {"tap":".tap","press":".press","doubleTap":".doubleTap","longPress":".longPress"}[row["gesture"]]
        add(f'            InteractionCard(title: "{row["title"]}",')
        add(f'                            cardColor: Color(hex: "{row["cardColor"]}"),')
        add(f'                            ovalColor: Color(hex: "{row["ovalColor"]}"),')
        add(f'                            interaction: {gc}, endScale: {AN["endScale"]})')
    add("        }")
    add("        .padding(.horizontal, 16)")
    add("        .frame(maxWidth: .infinity, maxHeight: .infinity)")
    add(f'        .background(Color(hex: "{A["background"]}"))')
    add("    }")
    add("}")
    add("")
    add("extension Color {")
    add("    init(hex: String) {")
    add("        let h = hex.trimmingCharacters(in: CharacterSet(charactersIn: \"#\"))")
    add("        let v = UInt64(h, radix: 16) ?? 0xFFFFFF")
    add("        self.init(.sRGB, red: Double((v>>16)&0xFF)/255, green: Double((v>>8)&0xFF)/255,")
    add("                  blue: Double(v&0xFF)/255, opacity: 1)")
    add("    }")
    add("    var isApproximatelyWhite: Bool {")
    add("        #if canImport(UIKit)")
    add("        var r: CGFloat=0,g: CGFloat=0,b: CGFloat=0,a: CGFloat=0")
    add("        UIColor(self).getRed(&r,green:&g,blue:&b,alpha:&a); return r>0.9&&g>0.9&&b>0.9")
    add("        #else")
    add("        return false")
    add("        #endif")
    add("    }")
    add("}")
    add("")
    add("#Preview { TouchOrigamiExampleView() }")
    return "\n".join(L)+"\n"

if __name__ == "__main__":
    ir = load(sys.argv[1] if len(sys.argv)>1 else "examples/TouchOrigamiExample.ir.json")
    out = sys.argv[2] if len(sys.argv)>2 else "examples/TouchOrigamiExample.generated.swift"
    pathlib.Path(out).write_text(gen(ir))
    print("wrote", out)
